"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import SupportsIndex, Union

_Shape = tuple[int, ...]
_ShapeLike = Union[SupportsIndex, Sequence[SupportsIndex]]
