"""
This type stub file was generated by pyright.
"""

from ._array_object import Array

def take(x: Array, indices: Array, /, *, axis: Optional[int] = ...) -> Array:
    """
    Array API compatible wrapper for :py:func:`np.take <numpy.take>`.

    See its docstring for more information.
    """
    ...

